// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: storage.proto

#include "storage.pb.h"
#include "storage.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace storage {

static const char* MetadataService_method_names[] = {
  "/storage.MetadataService/CreateFile",
  "/storage.MetadataService/GetFile",
  "/storage.MetadataService/DeleteFile",
  "/storage.MetadataService/ListFiles",
  "/storage.MetadataService/GetChunkLocations",
};

std::unique_ptr< MetadataService::Stub> MetadataService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MetadataService::Stub> stub(new MetadataService::Stub(channel, options));
  return stub;
}

MetadataService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateFile_(MetadataService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFile_(MetadataService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteFile_(MetadataService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListFiles_(MetadataService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetChunkLocations_(MetadataService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MetadataService::Stub::CreateFile(::grpc::ClientContext* context, const ::storage::CreateFileRequest& request, ::storage::FileMetadata* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::CreateFileRequest, ::storage::FileMetadata, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateFile_, context, request, response);
}

void MetadataService::Stub::async::CreateFile(::grpc::ClientContext* context, const ::storage::CreateFileRequest* request, ::storage::FileMetadata* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::CreateFileRequest, ::storage::FileMetadata, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFile_, context, request, response, std::move(f));
}

void MetadataService::Stub::async::CreateFile(::grpc::ClientContext* context, const ::storage::CreateFileRequest* request, ::storage::FileMetadata* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::FileMetadata>* MetadataService::Stub::PrepareAsyncCreateFileRaw(::grpc::ClientContext* context, const ::storage::CreateFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::FileMetadata, ::storage::CreateFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::FileMetadata>* MetadataService::Stub::AsyncCreateFileRaw(::grpc::ClientContext* context, const ::storage::CreateFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetadataService::Stub::GetFile(::grpc::ClientContext* context, const ::storage::GetFileRequest& request, ::storage::FileMetadata* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::GetFileRequest, ::storage::FileMetadata, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFile_, context, request, response);
}

void MetadataService::Stub::async::GetFile(::grpc::ClientContext* context, const ::storage::GetFileRequest* request, ::storage::FileMetadata* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::GetFileRequest, ::storage::FileMetadata, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFile_, context, request, response, std::move(f));
}

void MetadataService::Stub::async::GetFile(::grpc::ClientContext* context, const ::storage::GetFileRequest* request, ::storage::FileMetadata* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::FileMetadata>* MetadataService::Stub::PrepareAsyncGetFileRaw(::grpc::ClientContext* context, const ::storage::GetFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::FileMetadata, ::storage::GetFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::FileMetadata>* MetadataService::Stub::AsyncGetFileRaw(::grpc::ClientContext* context, const ::storage::GetFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetadataService::Stub::DeleteFile(::grpc::ClientContext* context, const ::storage::DeleteFileRequest& request, ::storage::DeleteFileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::DeleteFileRequest, ::storage::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteFile_, context, request, response);
}

void MetadataService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::storage::DeleteFileRequest* request, ::storage::DeleteFileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::DeleteFileRequest, ::storage::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, std::move(f));
}

void MetadataService::Stub::async::DeleteFile(::grpc::ClientContext* context, const ::storage::DeleteFileRequest* request, ::storage::DeleteFileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteFile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::DeleteFileResponse>* MetadataService::Stub::PrepareAsyncDeleteFileRaw(::grpc::ClientContext* context, const ::storage::DeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::DeleteFileResponse, ::storage::DeleteFileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteFile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::DeleteFileResponse>* MetadataService::Stub::AsyncDeleteFileRaw(::grpc::ClientContext* context, const ::storage::DeleteFileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteFileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetadataService::Stub::ListFiles(::grpc::ClientContext* context, const ::storage::ListFilesRequest& request, ::storage::ListFilesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::ListFilesRequest, ::storage::ListFilesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListFiles_, context, request, response);
}

void MetadataService::Stub::async::ListFiles(::grpc::ClientContext* context, const ::storage::ListFilesRequest* request, ::storage::ListFilesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::ListFilesRequest, ::storage::ListFilesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListFiles_, context, request, response, std::move(f));
}

void MetadataService::Stub::async::ListFiles(::grpc::ClientContext* context, const ::storage::ListFilesRequest* request, ::storage::ListFilesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListFiles_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::ListFilesResponse>* MetadataService::Stub::PrepareAsyncListFilesRaw(::grpc::ClientContext* context, const ::storage::ListFilesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::ListFilesResponse, ::storage::ListFilesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListFiles_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::ListFilesResponse>* MetadataService::Stub::AsyncListFilesRaw(::grpc::ClientContext* context, const ::storage::ListFilesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListFilesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MetadataService::Stub::GetChunkLocations(::grpc::ClientContext* context, const ::storage::GetChunkLocationsRequest& request, ::storage::ChunkLocations* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::GetChunkLocationsRequest, ::storage::ChunkLocations, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetChunkLocations_, context, request, response);
}

void MetadataService::Stub::async::GetChunkLocations(::grpc::ClientContext* context, const ::storage::GetChunkLocationsRequest* request, ::storage::ChunkLocations* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::GetChunkLocationsRequest, ::storage::ChunkLocations, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetChunkLocations_, context, request, response, std::move(f));
}

void MetadataService::Stub::async::GetChunkLocations(::grpc::ClientContext* context, const ::storage::GetChunkLocationsRequest* request, ::storage::ChunkLocations* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetChunkLocations_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::ChunkLocations>* MetadataService::Stub::PrepareAsyncGetChunkLocationsRaw(::grpc::ClientContext* context, const ::storage::GetChunkLocationsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::ChunkLocations, ::storage::GetChunkLocationsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetChunkLocations_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::ChunkLocations>* MetadataService::Stub::AsyncGetChunkLocationsRaw(::grpc::ClientContext* context, const ::storage::GetChunkLocationsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetChunkLocationsRaw(context, request, cq);
  result->StartCall();
  return result;
}

MetadataService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetadataService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetadataService::Service, ::storage::CreateFileRequest, ::storage::FileMetadata, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetadataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::CreateFileRequest* req,
             ::storage::FileMetadata* resp) {
               return service->CreateFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetadataService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetadataService::Service, ::storage::GetFileRequest, ::storage::FileMetadata, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetadataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::GetFileRequest* req,
             ::storage::FileMetadata* resp) {
               return service->GetFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetadataService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetadataService::Service, ::storage::DeleteFileRequest, ::storage::DeleteFileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetadataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::DeleteFileRequest* req,
             ::storage::DeleteFileResponse* resp) {
               return service->DeleteFile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetadataService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetadataService::Service, ::storage::ListFilesRequest, ::storage::ListFilesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetadataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::ListFilesRequest* req,
             ::storage::ListFilesResponse* resp) {
               return service->ListFiles(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MetadataService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MetadataService::Service, ::storage::GetChunkLocationsRequest, ::storage::ChunkLocations, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MetadataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::GetChunkLocationsRequest* req,
             ::storage::ChunkLocations* resp) {
               return service->GetChunkLocations(ctx, req, resp);
             }, this)));
}

MetadataService::Service::~Service() {
}

::grpc::Status MetadataService::Service::CreateFile(::grpc::ServerContext* context, const ::storage::CreateFileRequest* request, ::storage::FileMetadata* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetadataService::Service::GetFile(::grpc::ServerContext* context, const ::storage::GetFileRequest* request, ::storage::FileMetadata* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetadataService::Service::DeleteFile(::grpc::ServerContext* context, const ::storage::DeleteFileRequest* request, ::storage::DeleteFileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetadataService::Service::ListFiles(::grpc::ServerContext* context, const ::storage::ListFilesRequest* request, ::storage::ListFilesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MetadataService::Service::GetChunkLocations(::grpc::ServerContext* context, const ::storage::GetChunkLocationsRequest* request, ::storage::ChunkLocations* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* StorageNodeService_method_names[] = {
  "/storage.StorageNodeService/StoreChunk",
  "/storage.StorageNodeService/RetrieveChunk",
  "/storage.StorageNodeService/DeleteChunk",
  "/storage.StorageNodeService/ReplicateChunk",
  "/storage.StorageNodeService/HealthCheck",
};

std::unique_ptr< StorageNodeService::Stub> StorageNodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< StorageNodeService::Stub> stub(new StorageNodeService::Stub(channel, options));
  return stub;
}

StorageNodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StoreChunk_(StorageNodeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RetrieveChunk_(StorageNodeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteChunk_(StorageNodeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReplicateChunk_(StorageNodeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HealthCheck_(StorageNodeService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status StorageNodeService::Stub::StoreChunk(::grpc::ClientContext* context, const ::storage::StoreChunkRequest& request, ::storage::StoreChunkResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::StoreChunkRequest, ::storage::StoreChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StoreChunk_, context, request, response);
}

void StorageNodeService::Stub::async::StoreChunk(::grpc::ClientContext* context, const ::storage::StoreChunkRequest* request, ::storage::StoreChunkResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::StoreChunkRequest, ::storage::StoreChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StoreChunk_, context, request, response, std::move(f));
}

void StorageNodeService::Stub::async::StoreChunk(::grpc::ClientContext* context, const ::storage::StoreChunkRequest* request, ::storage::StoreChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StoreChunk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::StoreChunkResponse>* StorageNodeService::Stub::PrepareAsyncStoreChunkRaw(::grpc::ClientContext* context, const ::storage::StoreChunkRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::StoreChunkResponse, ::storage::StoreChunkRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StoreChunk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::StoreChunkResponse>* StorageNodeService::Stub::AsyncStoreChunkRaw(::grpc::ClientContext* context, const ::storage::StoreChunkRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStoreChunkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StorageNodeService::Stub::RetrieveChunk(::grpc::ClientContext* context, const ::storage::RetrieveChunkRequest& request, ::storage::ChunkData* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::RetrieveChunkRequest, ::storage::ChunkData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RetrieveChunk_, context, request, response);
}

void StorageNodeService::Stub::async::RetrieveChunk(::grpc::ClientContext* context, const ::storage::RetrieveChunkRequest* request, ::storage::ChunkData* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::RetrieveChunkRequest, ::storage::ChunkData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RetrieveChunk_, context, request, response, std::move(f));
}

void StorageNodeService::Stub::async::RetrieveChunk(::grpc::ClientContext* context, const ::storage::RetrieveChunkRequest* request, ::storage::ChunkData* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RetrieveChunk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::ChunkData>* StorageNodeService::Stub::PrepareAsyncRetrieveChunkRaw(::grpc::ClientContext* context, const ::storage::RetrieveChunkRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::ChunkData, ::storage::RetrieveChunkRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RetrieveChunk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::ChunkData>* StorageNodeService::Stub::AsyncRetrieveChunkRaw(::grpc::ClientContext* context, const ::storage::RetrieveChunkRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRetrieveChunkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StorageNodeService::Stub::DeleteChunk(::grpc::ClientContext* context, const ::storage::DeleteChunkRequest& request, ::storage::DeleteChunkResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::DeleteChunkRequest, ::storage::DeleteChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteChunk_, context, request, response);
}

void StorageNodeService::Stub::async::DeleteChunk(::grpc::ClientContext* context, const ::storage::DeleteChunkRequest* request, ::storage::DeleteChunkResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::DeleteChunkRequest, ::storage::DeleteChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteChunk_, context, request, response, std::move(f));
}

void StorageNodeService::Stub::async::DeleteChunk(::grpc::ClientContext* context, const ::storage::DeleteChunkRequest* request, ::storage::DeleteChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteChunk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::DeleteChunkResponse>* StorageNodeService::Stub::PrepareAsyncDeleteChunkRaw(::grpc::ClientContext* context, const ::storage::DeleteChunkRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::DeleteChunkResponse, ::storage::DeleteChunkRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteChunk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::DeleteChunkResponse>* StorageNodeService::Stub::AsyncDeleteChunkRaw(::grpc::ClientContext* context, const ::storage::DeleteChunkRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteChunkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StorageNodeService::Stub::ReplicateChunk(::grpc::ClientContext* context, const ::storage::ReplicateChunkRequest& request, ::storage::ReplicateChunkResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::ReplicateChunkRequest, ::storage::ReplicateChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReplicateChunk_, context, request, response);
}

void StorageNodeService::Stub::async::ReplicateChunk(::grpc::ClientContext* context, const ::storage::ReplicateChunkRequest* request, ::storage::ReplicateChunkResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::ReplicateChunkRequest, ::storage::ReplicateChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplicateChunk_, context, request, response, std::move(f));
}

void StorageNodeService::Stub::async::ReplicateChunk(::grpc::ClientContext* context, const ::storage::ReplicateChunkRequest* request, ::storage::ReplicateChunkResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplicateChunk_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::ReplicateChunkResponse>* StorageNodeService::Stub::PrepareAsyncReplicateChunkRaw(::grpc::ClientContext* context, const ::storage::ReplicateChunkRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::ReplicateChunkResponse, ::storage::ReplicateChunkRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReplicateChunk_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::ReplicateChunkResponse>* StorageNodeService::Stub::AsyncReplicateChunkRaw(::grpc::ClientContext* context, const ::storage::ReplicateChunkRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReplicateChunkRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status StorageNodeService::Stub::HealthCheck(::grpc::ClientContext* context, const ::storage::HealthCheckRequest& request, ::storage::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::storage::HealthCheckRequest, ::storage::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void StorageNodeService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::storage::HealthCheckRequest* request, ::storage::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::storage::HealthCheckRequest, ::storage::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void StorageNodeService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::storage::HealthCheckRequest* request, ::storage::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::storage::HealthCheckResponse>* StorageNodeService::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::storage::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::storage::HealthCheckResponse, ::storage::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::storage::HealthCheckResponse>* StorageNodeService::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::storage::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

StorageNodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageNodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageNodeService::Service, ::storage::StoreChunkRequest, ::storage::StoreChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StorageNodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::StoreChunkRequest* req,
             ::storage::StoreChunkResponse* resp) {
               return service->StoreChunk(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageNodeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageNodeService::Service, ::storage::RetrieveChunkRequest, ::storage::ChunkData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StorageNodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::RetrieveChunkRequest* req,
             ::storage::ChunkData* resp) {
               return service->RetrieveChunk(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageNodeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageNodeService::Service, ::storage::DeleteChunkRequest, ::storage::DeleteChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StorageNodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::DeleteChunkRequest* req,
             ::storage::DeleteChunkResponse* resp) {
               return service->DeleteChunk(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageNodeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageNodeService::Service, ::storage::ReplicateChunkRequest, ::storage::ReplicateChunkResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StorageNodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::ReplicateChunkRequest* req,
             ::storage::ReplicateChunkResponse* resp) {
               return service->ReplicateChunk(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      StorageNodeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< StorageNodeService::Service, ::storage::HealthCheckRequest, ::storage::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](StorageNodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::storage::HealthCheckRequest* req,
             ::storage::HealthCheckResponse* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
}

StorageNodeService::Service::~Service() {
}

::grpc::Status StorageNodeService::Service::StoreChunk(::grpc::ServerContext* context, const ::storage::StoreChunkRequest* request, ::storage::StoreChunkResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageNodeService::Service::RetrieveChunk(::grpc::ServerContext* context, const ::storage::RetrieveChunkRequest* request, ::storage::ChunkData* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageNodeService::Service::DeleteChunk(::grpc::ServerContext* context, const ::storage::DeleteChunkRequest* request, ::storage::DeleteChunkResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageNodeService::Service::ReplicateChunk(::grpc::ServerContext* context, const ::storage::ReplicateChunkRequest* request, ::storage::ReplicateChunkResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status StorageNodeService::Service::HealthCheck(::grpc::ServerContext* context, const ::storage::HealthCheckRequest* request, ::storage::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace storage

